"""Utility to post-process Voronoi images produced by `voronoi_qt.py`.

This script finds JPGs produced by the GUI (file names starting with
``Voronoi_original`` or ``Voronoi_warped``), crops them to the square
box removing the header saying "Original Voronoi" or "Warped Voronoi", 
and writes two bordered variants for each image (orange and blue color 
borders) into a per-pair output directory named ``pair_<n>``.
"""

import os
from PIL import Image, ImageOps

# User settings
INPUT_DIR = "dasFoto/"     # folder with input JPGs

# Square crop tuning (DO NOT MODIFY -- these are specific to this set of images generated by voronoi_qt.py)
VERT_OFFSET = 12        # move crop box down (pixels)
SCALE = 0.95              # amount of image width/height to keep

# Borders
COLOR_BORDER_WIDTH = 6   # px around the square
MM_WHITE_BORDER = 5       # white border (mm)
DPI = 300                 # used for mm → px conversion

BORDER_COLORS = {
    "orange": (255, 173, 91),
    "blue":   (128, 192, 255),
    "clean":  (0, 0, 0) # black border 
}

def mm_to_px(mm, dpi=DPI):
    return int((mm / 25.4) * dpi)

white_padding = mm_to_px(MM_WHITE_BORDER)

def square_crop(img, offset=VERT_OFFSET, scale=SCALE):
    w, h = img.size
    side = int(min(w, h) * scale)

    # centered horizontally
    left = (w - side) // 2
    right = left + side

    # vertically shifted down by offset
    top = (h - side) // 2 + offset
    bottom = top + side

    crop_box = (left, top, right, bottom)
    return img.crop(crop_box)

def add_color_border(img, rgb):
    return ImageOps.expand(img, border=COLOR_BORDER_WIDTH, fill=rgb)


def add_white_border(img):
    return ImageOps.expand(img, border=white_padding, fill="white")

def get_pair_number(filename):
    for part in filename.split("_"):
        if part.startswith("pair"):
            return part.replace("pair", "").split(".")[0]
    return None

def main():
    all_files = os.listdir(INPUT_DIR)

    for fname in all_files:
        if not fname.lower().endswith(".jpg"):
            continue
        if "Voronoi_original" not in fname and "Voronoi_warped" not in fname:
            continue

        pair_num = get_pair_number(fname)
        if pair_num is None:
            continue

        out_dir = f"pair_{pair_num}"
        os.makedirs(out_dir, exist_ok=True)

        img = Image.open(os.path.join(INPUT_DIR, fname))

        # Step 1 — Square crop
        sq = square_crop(img)

        # # Save clean cropped version (no borders)
        # base_clean = os.path.join(out_dir, fname.replace(".jpg", "_clean.jpg"))
        # sq.save(base_clean)

        # Step 2 & 3 — Colored border → white padding
        for cname, rgb in BORDER_COLORS.items():
            color_bordered = add_color_border(sq, rgb)
            final = add_white_border(color_bordered)
            outname = fname.replace(".jpg", f"_{cname}_border.jpg")
            final.save(os.path.join(out_dir, outname))

    print("✔ All pairs processed!")


if __name__ == '__main__':
    main()